geometry_msgs/PoseArray sorted_goal_poses # Goal Poses before grip, sorted by scores
geometry_msgs/PoseArray sorted_grip_poses # Grip Poses sort by scores
---
int8 passed_index # Return first index that pass